### ISSUE TITLE
markdown headings

### ISSUE THREAD

**Issue by xguntis** [oleander/markdown-to-bbcode-js#3]
Hi @oleander 

I've been looking for markdown to BBCode converter for ages and yours is the closest one to what I need. I wanted to add H1 and other heading tags, but for some reason, it doesn't work.

Here is what I changed in markdown.js file:
line 10
```
methods: ["url", "italic", "underscore", "strong", "quote", "image", "h1"],
```
after line 25 insert
```
  self.h1 = function(content) {
    return content.replace(/# ?(.*)/gm, '[size=120][b]$1[/b][/size]');
  };
```

It is ignoring my 
```
# Heading1
```
Is my regex wrong or am I missing something else?

**Comment by xguntis** [comment]
Never mind, actually it worked just had to clear the browser cache.

**Comment by oleander** [comment]
Good that you managed to solve it.
